--CREATE DATABASE LOGDETAILS;
USE LOGDETAILS;
--CREATE TABLE Users (
--    Id INT PRIMARY KEY IDENTITY,
--    Name NVARCHAR(100),
--    Email NVARCHAR(100),
--    Password NVARCHAR(100)
--);
SELECT * FROM Users;