--CREATE DATABASE LOGINFORM;
USE LOGINFORM;
--CREATE TABLE DETAILS (
--    ID INT IDENTITY(1,1) PRIMARY KEY,
--    USERNAME VARCHAR(50) NOT NULL,
--    PASSWORD VARCHAR(100) NOT NULL
--);
SELECT * FROM DETAILS;
